name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true  # Allow the whole job to continue even if tests fail
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov flake8 mypy
          pip install -e .
      
      - name: Run flake8
        continue-on-error: true  # Allow this step to fail
        run: |
          # First run with just the error count
          flake8 agentix --count --show-source --statistics
          # Then run for real (this will determine pass/fail)
          flake8 agentix
      
      - name: Run mypy
        continue-on-error: true  # Allow this step to fail
        run: mypy agentix
      
      - name: Run tests
        continue-on-error: true  # Allow this step to fail
        run: pytest tests/ --cov=agentix --cov-report=xml
      
      - name: Upload coverage to Codecov
        continue-on-error: true  # Allow this step to fail
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false  # Don't fail if coverage upload fails 